/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TagsLazyImport = createFileRoute('/tags')()
const SettingsLazyImport = createFileRoute('/settings')()
const ProjectsLazyImport = createFileRoute('/projects')()
const NextLazyImport = createFileRoute('/next')()
const CompletedLazyImport = createFileRoute('/completed')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TagsLazyRoute = TagsLazyImport.update({
  path: '/tags',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tags.lazy').then((d) => d.Route))

const SettingsLazyRoute = SettingsLazyImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))

const ProjectsLazyRoute = ProjectsLazyImport.update({
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/projects.lazy').then((d) => d.Route))

const NextLazyRoute = NextLazyImport.update({
  path: '/next',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/next.lazy').then((d) => d.Route))

const CompletedLazyRoute = CompletedLazyImport.update({
  path: '/completed',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/completed.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/completed': {
      id: '/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof CompletedLazyImport
      parentRoute: typeof rootRoute
    }
    '/next': {
      id: '/next'
      path: '/next'
      fullPath: '/next'
      preLoaderRoute: typeof NextLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/completed': typeof CompletedLazyRoute
  '/next': typeof NextLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/tags': typeof TagsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/completed': typeof CompletedLazyRoute
  '/next': typeof NextLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/tags': typeof TagsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/completed': typeof CompletedLazyRoute
  '/next': typeof NextLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/tags': typeof TagsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/completed' | '/next' | '/projects' | '/settings' | '/tags'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/completed' | '/next' | '/projects' | '/settings' | '/tags'
  id:
    | '__root__'
    | '/'
    | '/completed'
    | '/next'
    | '/projects'
    | '/settings'
    | '/tags'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CompletedLazyRoute: typeof CompletedLazyRoute
  NextLazyRoute: typeof NextLazyRoute
  ProjectsLazyRoute: typeof ProjectsLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  TagsLazyRoute: typeof TagsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CompletedLazyRoute: CompletedLazyRoute,
  NextLazyRoute: NextLazyRoute,
  ProjectsLazyRoute: ProjectsLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  TagsLazyRoute: TagsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/completed",
        "/next",
        "/projects",
        "/settings",
        "/tags"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/completed": {
      "filePath": "completed.lazy.tsx"
    },
    "/next": {
      "filePath": "next.lazy.tsx"
    },
    "/projects": {
      "filePath": "projects.lazy.tsx"
    },
    "/settings": {
      "filePath": "settings.lazy.tsx"
    },
    "/tags": {
      "filePath": "tags.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
