/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TableViewLazyImport = createFileRoute('/table-view')()
const KanbanBoardLazyImport = createFileRoute('/kanban-board')()
const GanttDiagramLazyImport = createFileRoute('/gantt-diagram')()
const CalendarLazyImport = createFileRoute('/calendar')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TableViewLazyRoute = TableViewLazyImport.update({
  path: '/table-view',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/table-view.lazy').then((d) => d.Route))

const KanbanBoardLazyRoute = KanbanBoardLazyImport.update({
  path: '/kanban-board',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/kanban-board.lazy').then((d) => d.Route))

const GanttDiagramLazyRoute = GanttDiagramLazyImport.update({
  path: '/gantt-diagram',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/gantt-diagram.lazy').then((d) => d.Route))

const CalendarLazyRoute = CalendarLazyImport.update({
  path: '/calendar',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/calendar.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarLazyImport
      parentRoute: typeof rootRoute
    }
    '/gantt-diagram': {
      id: '/gantt-diagram'
      path: '/gantt-diagram'
      fullPath: '/gantt-diagram'
      preLoaderRoute: typeof GanttDiagramLazyImport
      parentRoute: typeof rootRoute
    }
    '/kanban-board': {
      id: '/kanban-board'
      path: '/kanban-board'
      fullPath: '/kanban-board'
      preLoaderRoute: typeof KanbanBoardLazyImport
      parentRoute: typeof rootRoute
    }
    '/table-view': {
      id: '/table-view'
      path: '/table-view'
      fullPath: '/table-view'
      preLoaderRoute: typeof TableViewLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/calendar': typeof CalendarLazyRoute
  '/gantt-diagram': typeof GanttDiagramLazyRoute
  '/kanban-board': typeof KanbanBoardLazyRoute
  '/table-view': typeof TableViewLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/calendar': typeof CalendarLazyRoute
  '/gantt-diagram': typeof GanttDiagramLazyRoute
  '/kanban-board': typeof KanbanBoardLazyRoute
  '/table-view': typeof TableViewLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/calendar': typeof CalendarLazyRoute
  '/gantt-diagram': typeof GanttDiagramLazyRoute
  '/kanban-board': typeof KanbanBoardLazyRoute
  '/table-view': typeof TableViewLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/gantt-diagram'
    | '/kanban-board'
    | '/table-view'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/gantt-diagram' | '/kanban-board' | '/table-view'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/gantt-diagram'
    | '/kanban-board'
    | '/table-view'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CalendarLazyRoute: typeof CalendarLazyRoute
  GanttDiagramLazyRoute: typeof GanttDiagramLazyRoute
  KanbanBoardLazyRoute: typeof KanbanBoardLazyRoute
  TableViewLazyRoute: typeof TableViewLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CalendarLazyRoute: CalendarLazyRoute,
  GanttDiagramLazyRoute: GanttDiagramLazyRoute,
  KanbanBoardLazyRoute: KanbanBoardLazyRoute,
  TableViewLazyRoute: TableViewLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/calendar",
        "/gantt-diagram",
        "/kanban-board",
        "/table-view"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/calendar": {
      "filePath": "calendar.lazy.tsx"
    },
    "/gantt-diagram": {
      "filePath": "gantt-diagram.lazy.tsx"
    },
    "/kanban-board": {
      "filePath": "kanban-board.lazy.tsx"
    },
    "/table-view": {
      "filePath": "table-view.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
