
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async addTask(description: string) : Promise<Task> {
    return await TAURI_INVOKE("add_task", { description });
},
async getProjects() : Promise<string[]> {
    return await TAURI_INVOKE("get_projects");
},
async getTask(taskUuid: string) : Promise<Task> {
    return await TAURI_INVOKE("get_task", { taskUuid });
},
async getTasks() : Promise<Task[]> {
    return await TAURI_INVOKE("get_tasks");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Annotation = { entry: string; description: string }
export type Task = { status: TaskStatus; uuid: string; entry: string; description: string; start?: string | null; end?: string | null; due?: string | null; until?: string | null; wait?: string | null; modified: string; scheduled?: string | null; recur: string | null; mask: string | null; imask: number | null; parent: string | null; project: string | null; priority: string | null; depends: string | null; tags: string[] | null; annotations: Annotation[] | null; id: number; urgency: number }
export type TaskGroup = { name: string | null; tasks: Task[] }
// BOM
export enum TaskStatus {
  PENDING = "pending",
  DELETED = "deleted",
  COMPLETED = "completed",
  WAITING = "waiting",
  RECURRING = "recurring",
}
// EOM

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
